### ISSUE TITLE
Tracking issue for zOS CI runs

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#1452]
* **Version**: v1.x
* **Platform**: zOS

In setting up CI resting of libuv on zOS there we see some failures. Some may be related to setup some real issues.  This is a tracking issue for us to work through them to fix environment or implementation as appropriate.

Working job is:
https://ci.nodejs.org/job/libuv-test-commit-zos/94/nodes=zos-s390x/console

The idea is to check of tests off as they are resolved.

The following tests failed:

- [ ] not ok 54 - tcp_open_bound
```
# exit code 3
# Output from process `tcp_open_bound`:
# Assertion failed in ../test/test-tcp-open.c on line 239: 0 == uv_listen((uv_stream_t*) &server, 128, NULL)
# CEE5207E The signal SIGABRT was received.
```

- [x] not ok 73 - tcp_oob
```
# exit code 3
# Output from process `tcp_oob`:
# Assertion failed in ../test/test-tcp-oob.c on line 59: nread > 0
# CEE5207E The signal SIGABRT was received.
```
- [x] not ok 134 - timer_run_once
```
# exit code 3
# Output from process `timer_run_once`:
# Assertion failed in ../test/test-timer.c on line 284: 0 == uv_run(uv_default_loop(), UV_RUN_ONCE)
# CEE5207E The signal SIGABRT was received.
```
- [x] not ok 180 - hrtime
```
# exit code 3
# Output from process `hrtime`:
# Assertion failed in ../test/test-hrtime.c on line 49: diff > (uint64_t) 25 * NANOSEC / MILLISEC
# CEE5207E The signal SIGABRT was received.
```
- [x] not ok 210 - spawn_setgid_fails
```
# exit code 3
# Output from process `spawn_setgid_fails`:
# Assertion failed in ../test/test-spawn.c on line 1360: r == UV_EPERM
# CEE5207E The signal SIGABRT was received.
```
- [x] not ok 217 - spawn_reads_child_path
```
# exit code 3
# Output from process `spawn_reads_child_path`:
# exit_cb
# Assertion failed in ../test/test-spawn.c on line 69: exit_status == 1
# CEE5207E The signal SIGABRT was received.
```
- [x] not ok 248 - fs_chown
```
# exit code 3
# Output from process `fs_chown`:
# Assertion failed in ../test/test-fs.c on line 257: req->result == UV_EPERM
# CEE5207E The signal SIGABRT was received.
```

-  [ ] not ok 315 - fork_threadpool_queue_work_simple
```
# exit code 3
# Output from process `fork_threadpool_queue_work_simple`:
# Queue in 65724
# Running in 65724
# Queue in 65724
# Running in 65724
# CEE5207E The signal SIGABRT was received.
# Waited pid is 65729 with status 3
# Assertion failed in ../test/test-fork.c on line 86: WIFEXITED(child_stat)
# CEE5207E The signal SIGABRT was received.
```

**Comment by mhdawson** [comment]
Its quite likely that:

* not ok 248 - fs_chown
* not ok 210 - spawn_setgid_fails

are both due to setup on the zOS machines as opposed to functional failures.

**Comment by jBarz** [comment]
not ok 134 - timer_run_once
not ok 180 - hrtime
These should be fixed by https://github.com/libuv/libuv/pull/1453

**Comment by jBarz** [comment]
not ok 248 - fs_chown
This is fixed by https://github.com/libuv/libuv/pull/1454

**Comment by jBarz** [comment]
not ok 210 - spawn_setgid_fails
Fixed by https://github.com/libuv/libuv/pull/1456

**Comment by mhdawson** [comment]
One more failure in the run today:

not ok 54 - tcp_open_bound
# exit code 3
# Output from process `tcp_open_bound`:
# Assertion failed in ../test/test-tcp-open.c on line 239: 0 == uv_listen((uv_stream_t*) &server, 128, NULL)
# CEE5207E The signal SIGABRT was received.

**Comment by mhdawson** [comment]
the spawn_reads_child_path failure was due to job setup, run-tests need to be in path to be able to be called recursively.

**Comment by mhdawson** [comment]
The tests I had to exclude now also run ok (1 still fails).  Updated description above.

ok 29 - tty # SKIP Cannot open /dev/tty as read-only: EDC5128I No such device.

ok 314 - fork_fs_events_file_parent_child # SKIP Filesystem watching not supported on this platform.
not ok 315 - fork_threadpool_queue_work_simple
# exit code 3
# Output from process `fork_threadpool_queue_work_simple`:
# Queue in 65724
# Running in 65724
# Queue in 65724
# Running in 65724
# CEE5207E The signal SIGABRT was received.
# Waited pid is 65729 with status 3
# Assertion failed in ../test/test-fork.c on line 86: WIFEXITED(child_stat)
# CEE5207E The signal SIGABRT was received.

**Comment by mhdawson** [comment]
Just so we have it captured somewhere semi-permanent, the current ci job set that runs the job:

```sh
#!/u/iojs/runAsciiBash
#!/NODEJS2/bin/bash
set -e
set -x

# install gyp as a prereq
rm -rf build
mkdir build
cd build
git clone git://github.com/jBarz/gyp.git
cd ..

export GYP_DEFINES="OS=os390 gyp_parallel_support=False"
python ./gyp_uv.py --no-parallel -f make -Duv_library=static_library
BUILDTYPE=Release make V=1 -C out run-tests
# the tests need to recursively call run-tests so make sure it can be run
# from the current directory
export PATH=$WORKSPACE:$WORKSPACE/out/Release:$PATH
ln -s out/Release/run-tests run-tests
run-tests
```

**Comment by mhdawson** [comment]
Note that we will be contributing the deltas needed to gyp that are currently in git://github.com/jBarz/gyp.git.

**Comment by jBarz** [comment]
not ok 73 - tcp_oob
fix is https://github.com/libuv/libuv/pull/1484

**Comment by jBarz** [comment]
not ok 54 - tcp_open_bound
fix in https://github.com/libuv/libuv/pull/1348

**Comment by mhdawson** [comment]
Down to 2 failures :)

**Comment by jBarz** [comment]
fork_threadpool_queue_work_simple
fix is https://github.com/libuv/libuv/pull/1596

**Comment by bnoordhuis** [comment]
One test failure remaining:

https://ci.nodejs.org/job/libuv-test-commit-zos/276/nodes=zos-s390x/console
```
not ok 233 - tcp_open_bound
# exit code 3
# Output from process `tcp_open_bound`:
# Assertion failed in ../test/test-tcp-open.c on line 239: 0 == uv_listen((uv_stream_t*) &server, 128, NULL)
# CEE5207E The signal SIGABRT was received.
```

**Comment by jBarz** [comment]
Is that from this PR? https://github.com/libuv/libuv/pull/1640
If yes, then it needs to be rebased.

**Comment by mhdawson** [comment]
I think this can now be closed. All tests should be passing (although for old branches we may see the last failures in a few runs unless they are rebased).
