### ISSUE TITLE
issues to fix on libuv master

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#2655]
Discovered in the process of working on https://github.com/libuv/libuv/pull/2649:

- [x] The tests from #849 are failing on my machine due to a mistaken expectation on the reliability of IEEE floating point math on an x87
- [x] (#3246) The #2492 tests need to be added to test/test-list.h
- [x] The "remove support for FreeBSD < 10" PR needs to be repeated (#984)
- [x] The switch from gnu89 to gnu99 PR needs to be repeated (in uv.gyp)
- [ ] affinity tests on win10-vs2017-arm64 are broken
- [x] (#3247) need to fix thread-affinity support on android:
  `r = sched_getaffinity(pthread_gettid_np(pthread_self()), sizeof(cpuset), &cpuset);`
- [ ] need to remove VS2013 from CI (https://github.com/libuv/libuv/pull/966)

**Comment by vtjnash** [comment]
I am going to call this list complete enough
