### ISSUE TITLE
Release proposal: v1.44.0

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#3452]
We have some very notable changes:

- [x] build regression fixes for various platform updates (#3428, #3419, #3423, #3413, #3431)
- [x] support for GNU/Hurd (https://github.com/libuv/libuv/pull/3450)
- [x] release tool improvements (https://github.com/libuv/libuv-release-tool/pull/13)
- [x] better performing rw locks on Win32 (#3383)
- [x] support for posix_spawn API (https://github.com/libuv/libuv/pull/3257)
- [ ] TCP resource management bug https://github.com/libuv/libuv/pull/3462
- [x] #3506 regression on OpenBSD
- [x] https://github.com/libuv/libuv/pull/3499

among other minor commits.

**Comment by bnoordhuis** [comment]
The neovim people seem to have hit a regression on openbsd in neovim/neovim#17219.

**Comment by clason** [comment]
...which it looks like is fixed by https://github.com/libuv/libuv/pull/3428.

**Comment by bnoordhuis** [comment]
Nice, thanks for investigating. One more reason to get the release out. :-)

**Comment by cjihrig** [comment]
libuv Jenkins CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2221/. Only the `ipc_closed_handle` test failed, which is nothing new.

Node.js + libuv integration CI: there is a green run between https://ci.nodejs.org/view/libuv/job/libuv-in-node/201/ and https://ci.nodejs.org/view/libuv/job/libuv-in-node/203/.

:shipit:

**Comment by drfloob** [comment]
Hello! Is there anything holding up the release at this point?

**Comment by vtjnash** [comment]
Turned out to need a small bugfix still, which I missed in my reviews

How is https://github.com/libuv/libuv/pull/3462 going?

**Comment by cjihrig** [comment]
If there are still some things waiting to land, maybe we should cut a release to address the regression and the other changes can go out in the next release?

**Comment by bnoordhuis** [comment]
Yes, let's do that. #3462 isn't very important and #3257 isn't ready yet, it looks like.

**Comment by vtjnash** [comment]
https://github.com/libuv/libuv/pull/3257 is not far

**Comment by cjihrig** [comment]
Can we quantify "not far" here? Are you opposed to cutting two separate releases? I'm happy to take over this one if that will help.

**Comment by jamessan** [comment]
> ...which it looks like is fixed by #3428.

That fixed the crashes we were seeing, but now the problem has changed to hangs.  Reverting back to 1.42.0 gets things stable again.  I can try and bisect what specifically introduced the problem.

I'm not sure if you have people that support the OpenBSD side of things, but it might be good to have it in CI.  We use sr.ht for that (and FreeBSD) in neovim.

**Comment by bnoordhuis** [comment]
> I'm not sure if you have people that support the OpenBSD side of things

Don't think so. Volunteers welcome, of course. :-)

**Comment by bnoordhuis** [comment]
I expect that needs someone to set up accounts, credentials, etc.? I'm not volunteering but I'm happy to answer questions of anyone who does.

**Comment by bnoordhuis** [comment]
On the subject of the release: #3257 seems to have left a number of systems in a broken state. I'm inclined to revert, release, re-apply and sort out the damage later. The last release was three months ago, I don't want to keep stacking up things indefinitely.

@vtjnash @cjihrig Your thoughts?

**Comment by vtjnash** [comment]
There is an easy fall-back for that, just unexpected to need it for something required by POSIX over 20 years ago

**Comment by cjihrig** [comment]
+1 to reverting and releasing as soon as we can do so.

Regarding OpenBSD CI - is that something we could incorporate into the GitHub Actions CI?

**Comment by jamessan** [comment]
> Regarding OpenBSD CI - is that something we could incorporate into the GitHub Actions CI?

After a little searching, I found https://github.com/cross-platform-actions/action which looks promising.

**Comment by cjihrig** [comment]
I don't want to sidetrack this issue too much. Would you mind opening a new issue regarding OpenBSD in the CI. We already have a [QEMU based CI](https://github.com/libuv/libuv/blob/c40f8cb9f8ddf69d116952f8924a11ec0623b445/.github/workflows/CI.yml#L69-L118) that we might be able to extend.

**Comment by vtjnash** [comment]
We are hopefully closing in on a release, since I have prepared a fix that simply does detection if it is available in the build environment (https://github.com/libuv/libuv/pull/3512)

However, https://github.com/libuv/libuv/pull/3499 also broke zOS, so we still not quite converging to a stable state yet.

**Comment by vtjnash** [comment]
CI looks good now:
https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2233/
https://ci.nodejs.org/view/libuv/job/libuv-in-node/209/
